### ISSUE TITLE
Használd a saját email címed

### ISSUE THREAD

**Issue by BaloghTamas** [gyeresicsaba/FootballDataMobilLab#1]
https://github.com/gyeresicsaba/FootballDataMobilLab/blob/049ea69cc11066bc17f067ab25d456f4124c78ac/.travis.yml#L33

Ha egy az egyben copy pasteled a travis configot, akkor bizony én fogom kapni a leveleket...

**Comment by gyeresicsaba** [comment]
Ne haragudj, későn vettem észre, átírtam. :)
